name: Build C# EXE

on:
  push:
    branches: [ "main" ]   # 当推送到 main 分支时触发
  workflow_dispatch:       # 允许手动触发

jobs:
  build:
    runs-on: windows-latest   # 使用 Windows 环境

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 编译为 EXE
        shell: cmd
        run: |
          :: 使用 .NET Framework 的 csc 编译器（系统自带）
          set csc=%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\csc.exe
          if not exist "%csc%" set csc=%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\csc.exe
          "%csc%" /target:winexe /out:FileBatchPrinter.exe Program.cs /reference:System.Windows.Forms.dll /reference:System.Drawing.dll

      - name: 上传生成的 EXE
        uses: actions/upload-artifact@v4
        with:
          name: FileBatchPrinter
          path: FileBatchPrinter.exe
